 language: go

go:
  - 1.5.3
  - 1.6
# - tip # NOTE: disabled - see https://github.com/travis-ci/gimme/issues/38

install:
  - go get -t -v ./...
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/lint/golint
  - go get labix.org/v2/mgo/bson
  - go get github.com/clbanning/x2j
  - go get github.com/ugorji/go/codec
  
before_script:
    - sudo apt-get install phantomjs
    - npm install karma karma-jasmine@2_0 jasmine-fixture jasmine-core phantomjs karma-phantomjs-launcher gulp

script:
  - go test -v -short ./...
  - go vet ./...
  - GOFMT=$(gofmt -d -s .) && echo $GOFMT && test -z "$GOFMT"
  - cd client
  - gulp build-test
  - ./node_modules/karma/bin/karma start --browsers PhantomJS --single-run